name: Install FMddl-MAAutoGirlsFrontLine

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  install:
    needs: meta
    runs-on: macos-latest
    strategy:
      matrix:
        os: [win, osx, linux]
        arch: [arm64, x64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}

      - name: Download FMddl-MAA Release
        uses: robinraju/release-downloader@v1
        with:
          repository: Fufu-OuO/FMddl-MAAutoGirlsFrontLine
          fileName: "FMddl-MAA-*-${{ matrix.os }}-${{ matrix.arch }}.zip"
          latest: true
          out-file-path: "download"
          extract: true

          # 复制下载的文件到安装目录
          cp -r download/* install/
          
          # 复制资源文件
          cp -r assets install/
          cp -r resource install/

      # 上传生成的安装包
      - uses: actions/upload-artifact@v4
        with:
          name: FMddl-MAA-${{ matrix.os }}-${{ matrix.arch }}
          path: "install"

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Package Installers
        run: |
          cd artifacts
          for dir in *; do
            # 压缩包命名为 FMddl-MAA-v0.1.1-win-x64.zip 格式
            zip -r "../FMddl-MAA-${{ needs.meta.outputs.tag }}-${dir}.zip" "$dir"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
          tag_name: ${{ needs.meta.outputs.tag }}
          generate_release_notes: true